default:
  menubar: false
  toolbar:
    - fontselect | fontsizeselect | bold italic underline strikethrough | forecolor backcolor
    - undo redo | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent | link image
  plugins:
    - image
    - link
    - lists
    - textcolor colorpicker
    - colorpicker
  font_formats: "微软雅黑='微软雅黑';宋体='宋体';黑体='黑体';仿宋='仿宋';楷体='楷体';隶书='隶书';幼圆='幼圆';Arial='Arial';"
