default: &default
  appid: <%= ENV['WCPC_WECHAT_APPID'] %>
  secret: <%= ENV['WCPC_WECHAT_SECRET'] %>
  token:  <%= ENV['WCPC_WECHAT_TOKEN'] %>
  access_token: <%= ENV['WCPC_WECHAT_ACCESS_TOKEN'] %>
  jsapi_ticket: <%= ENV['WCPC_WECHAT_JSAPI_TICKET'] %>

production:
  appid: <%= ENV['WCPC_WECHAT_APPID'] %>
  secret: <%= ENV['WCPC_WECHAT_SECRET'] %>
  token:   <%= ENV['WCPC_WECHAT_TOKEN'] %>
  access_token: <%= ENV['WCPC_WECHAT_ACCESS_TOKEN'] %>
  jsapi_ticket: <%= ENV['WCPC_WECHAT_JSAPI_TICKET'] %>
  oauth2_cookie_duration: <%= ENV['WCPC_WECHAT_OAUTH2_COOKIE_DURATION'] %> # seconds
  trusted_domain_fullname: "http://wcpc.getstore.cn"

development:
  <<: *default
  #trusted_domain_fullname: <%= ENV['WECHAT_TRUSTED_DOMAIN_FULLNAME'] %>
development_hui:
  <<: *default
  #trusted_domain_fullname: <%= ENV['WECHAT_TRUSTED_DOMAIN_FULLNAME'] %>

test:
  <<: *default
