# More option see https://github.com/Eric-Guo/wechat#menu-create
button:
 -
  type: "view"
  name: "睡照大赛"
  url:  "http://wx-wcpc.getstore.cn/"
 -
  type: "view"
  name: "线上商场"
  url:  "https://weidian.com/s/981175353?wfr=c&ifr=shopdetail"
